### ISSUE TITLE
Plugin is rendering wrong urls in sitemap if urlPrefix is set

### ISSUE THREAD

**Issue by koboldt** [gammastream/scully-plugins#1]
Hi,

i am new to scully.io and tried your plugin. But if i define my sitemapOptions and use an urlPrefix 

```
const sitemapOptions = {
  urlPrefix: 'http://localhost'
}
```

then the url in the sitemap.xml is rendered like this:

```
<url>
    <loc>http:\localhost\foo\bar</loc>
    <changefreq>monthly</changefreq>
    <lastmod>2020-03-02T21:30:17.232Z</lastmod>
    <priority>0.5</priority>
</url>
```

I think it might be better to use [url-join](https://www.npmjs.com/package/url-join) instead of path.join in order to concatenate the url/loc.

Kind regards

**Comment by msacket** [comment]
Thanks @koboldt, good point.  I'll get that fixed asap.
