### ISSUE TITLE
feat (sitemap): add an option to manage the seoHrefOptimise scully plugin

### ISSUE THREAD

**Issue by pegaltier** [gammastream/scully-plugins#11]
When we use the scully plugin seoHrefOptimise then the urls are rewritten with a slash at the end but the sitemap is still generated without the slash.

**Comment by msacket** [comment]
Hi @pegaltier.  In the latest version, I've added a `trailingSlash` flag.  Setting that `true` will add a trailing slash to the supplied route.  If that doesn't meet your needs, reopen this and I'll take another look.
