### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by Splaktar** [gammastream/scully-plugins#12]
Using the latest version of Scully and `@types/node` gives the following:
```
npm WARN @gammastream/scully-plugin-sitemap@1.0.2 requires a peer of @scullyio/scully@0.0.99 but none is installed. You must install peer dependencies yourself.
npm WARN @gammastream/scully-plugin-sitemap@1.0.2 requires a peer of @types/node@^7.10.10 but none is installed. You must install peer dependencies yourself.
npm WARN @gammastream/scully-plugin-sitemap@1.0.2 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
```
I'm not sure if there is a specific reason for requiring the old version of NodeJS types and not something that supports the latest (`"@types/node": "^14.0.27",`)?

Scully `1.0.0-beta.0` is now available and is marked as not supported by `1.0.2` of this library.

I know that Scully had issues with `tslib@2.0.0`, but it's something that it will need to support at some point (and the beta may have fixed this). But this library doesn't support this new tslib version.

Thank you for your work in maintaining this useful plugin!

**Comment by msacket** [comment]
Hi @Splaktar,  I appreciate the information.  I believe I have the dependencies corrected.  It's a bit of a challenge keeping up with the continuous stream of updates. Version `1.0.4` is the one you'll want.

**Comment by Splaktar** [comment]
Thanks, I'll check it out.
