### ISSUE TITLE
Scully: importy moved (@scullyio/scully => @scullyio/scully/lib/*)

### ISSUE THREAD

**Issue by d-koppenhagen** [gammastream/scully-plugins#4]
Hi, within the latest published scully version, the imports for e.g. `@scullyio/scully/routerPlugins` has been moved to `@scullyio/scully/lib/routerPlugins`.
Same with `'@scullyio/scully/utils/log'` = >`'@scullyio/scully/lib/utils/log'`.

This should be adjusted for all plugins

**Comment by msacket** [comment]
Thanks @d-koppenhagen, I'll get that updated asap.

**Comment by msacket** [comment]
Source and packages have been updated and pushed to npm.
