### ISSUE TITLE
Support different frequency settings

### ISSUE THREAD

**Issue by Splaktar** [gammastream/scully-plugins#5]
Ideally, I'd like to have something like this
- home page =`monthly`
- blog listing page = `daily`
- each blog post page =`weekly` or `monthly`

I guess that this could be done via globs, but I'm not sure where. Possibly in the Scully config file.

It would be nice to have something similar for priorties too.

**Comment by msacket** [comment]
Good idea.  I haven't tested this scenario, but you should be able to apply a separate configuration for various routes in Scully's routes section.  Right now, You'll probably have copy the whole configuration, but in a future release, you'd just have to specify what you want to override.

**Comment by msacket** [comment]
Hi @Splaktar .  I've pushed an update that allows you to update priority and frequency depending on the route.  This is a breaking update as it also includes updates to the way the plugin is configured.  Those changes were necessary based on the evolution of Scully's configuration enhancements.  If you find any issues or have other ideas, file an issue and I'll take a look.

```typescript
import { ScullyConfig, setPluginConfig } from '@scullyio/scully';
import { getSitemapPlugin } from '@gammastream/scully-plugin-sitemap';


const SitemapPlugin = getSitemapPlugin();
setPluginConfig(SitemapPlugin, {
    urlPrefix: 'https://gamma.stream',
    sitemapFilename: 'sitemap.xml',
    changeFreq: 'monthly',
    priority: ['1.0', '0.9', '0.8', '0.7', '0.6', '0.5', '0.4', '0.3', '0.2', '0.1', '0.0'],
    ignoredRoutes: ['/404'],
    routes: {
        '/products/:productId': {
            changeFreq: 'daily',
            priority: '0.9',
            sitemapFilename: 'sitemap-products.xml'
        },
    }
});

export const config: ScullyConfig = {
  projectRoot: './src',
  projectName: 'scully-plugins',
  outDir: './dist/static',
  routes: {
    '/products/:productId': {
        type: 'json',
        productId: {
            url: 'http://localhost:4200/assets/products.json',
            property: 'id',
        }
    }
  }
};
```

**Comment by Splaktar** [comment]
Thanks for the quick turn around!

Just FYI, in Angular v10, I'm seeing the following warning
```ts
Warning: Entry point '@gammastream/scully-plugin-sitemap' contains deep imports into '/Users/splaktar/Git/devintent/devintent/node_modules/@scullyio/scully/lib/utils/config'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

**Comment by Splaktar** [comment]
Works great! 💯  Thanks again.
