### ISSUE TITLE
Warning: Entry point '@gammastream/scully-plugin-http404' contains deep imports into 'node_modules/@scullyio/scully/lib/utils/config'

### ISSUE THREAD

**Issue by robertbaker** [gammastream/scully-plugins#8]
Warning: Entry point '@gammastream/scully-plugin-http404' contains deep imports into '/node_modules/@scullyio/scully/lib/utils/config'.

This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by msacket** [comment]
Fixed.
